services:
  debian:
    build:
      context: https://github.com/procrastinando/MailCow_DinD.git#main
    container_name: mailcow
    privileged: true
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - "25:25"
      - "8080:8080" # select the port that you prefer
      - "8443:8443" # select the port that you prefer
      - "587:587"
      - "993:993"
      - "465:465"
      - "995:995"
      - "4190:4190"
    networks:
      - npm-network
    volumes:
      - data:/mailcow-dockerized
      - docker:/var/lib/docker
      - npm-letsencrypt:/npm-letsencrypt
    restart: unless-stopped

volumes:
  data:
  docker:
  npm-letsencrypt:
    external: true

networks:
  npm-network:
    name: npm-network
    external: true
