services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt
    networks:
      - npm-network

volumes:
  npm-data:
    name: npm-data
  npm-letsencrypt:
    name: npm-letsencrypt

networks:
  npm-network:
    name: npm-network