services:
  dind:
    build:
      context: https://github.com/procrastinando/MailCow_DinD.git#main
    container_name: mailcow
    # Privileged mode is REQUIRED for DinD
    privileged: true
    ports:
      - "25:25"
      - "8078:8078" # select the port that you prefer
      - "8443:8443" # select the port that you prefer
      - "587:587"
      - "993:993"
      - "465:465"
      - "995:995"
      - "4190:4190"
    volumes:
      # Volume for mailcow data
      - data:/opt/mailcow-dockerized
      # External volume for Let's Encrypt
      - npm_letsencrypt:/npm_letsencrypt
      # Persists the INNER Docker's data (images, volumes, etc.)
      - docker:/var/lib/docker
    restart: unless-stopped

volumes:
  data:
  docker:
  npm_letsencrypt:
    external: true